minimum_orderly_version: "1.99.0"
plugins:
  orderly.sharedfile:
    lassasingledb: "Z:/Lassa/Databases/Single Extractions"
    lassadoubledb: "Z:/Lassa/Databases/Double Extractions"
    eboladoubledb2: "Z:/Ebola/databases/NEW DOUBLE EXTRACTION DATABASES"
    eboladoubledb: "Z:/Ebola/databases/Double extraction databases"
    ebolasingledb: "Z:/Ebola/databases/Single extraction databases"
    sarssingledb: "Y:/SARS/Databases/full_extraction"
    zikadoubledb: "C:/Users/kem22/OneDrive - Imperial College London/outbreaks/databases/Zika_dbs/Double_old"
    zikadoubledb2: "C:/Users/kem22/OneDrive - Imperial College London/outbreaks/databases/Zika_dbs/Double_new"
    #zikasingledb: "C:/Users/kem22/OneDrive - Imperial College London/outbreaks/databases/Zika_dbs/Single"
